namespace POEPART1_AAPD7112_MUNICIPALITY_SERVICES_APP.Forms
{
    partial class ReportIssuesForm
    {
        // Stores the components used by the Report Issues form.
        private System.ComponentModel.IContainer components = null;


        /**
         * Releases the resources used by the Report Issues form.
         *
         * This method ensures that the controls and other managed resources
         * created for the form are properly disposed of when the form is closed.
         */
        protected override void Dispose(bool disposing)
        {
            // Checks whether managed resources should be released and
            // whether the components container has been initialised.
            if (disposing && (components != null))
            {
                // Releases all resources stored in the components container.
                components.Dispose();
            }

            // Calls the base class Dispose method to complete the cleanup process.
            base.Dispose(disposing);
        }


        #region Windows Form Designer generated code


        /**
         * Initialises and configures all controls used on the Report Issues form.
         *
         * This method is generated by the Windows Forms Designer and defines
         * the appearance, position, size, properties and event handlers
         * associated with each control on the form.
         */
        private void InitializeComponent()
        {
            // Creates the title label displayed at the top of the form.
            this.lblTitle = new System.Windows.Forms.Label();

            // Creates the label identifying the location input field.
            this.lblLocation = new System.Windows.Forms.Label();

            // Creates the text box where the user enters the issue location.
            this.txtLocation = new System.Windows.Forms.TextBox();

            // Creates the label identifying the category selection.
            this.lblCategory = new System.Windows.Forms.Label();

            // Creates the ComboBox used to select a municipal issue category.
            this.cmbCategory = new System.Windows.Forms.ComboBox();

            // Creates the label identifying the issue description field.
            this.lblDescription = new System.Windows.Forms.Label();

            // Creates the RichTextBox used for entering a detailed description.
            this.rtbDescription = new System.Windows.Forms.RichTextBox();

            // Creates the label identifying the attachment section.
            this.lblAttachment = new System.Windows.Forms.Label();

            // Creates the button used to select an attachment.
            this.btnAttachFile = new System.Windows.Forms.Button();

            // Creates the label used to display the selected attachment filename.
            this.lblAttachmentName = new System.Windows.Forms.Label();

            // Creates the button used to remove a selected attachment.
            this.btnRemoveAttachment = new System.Windows.Forms.Button();

            // Creates the label identifying the estimated response time.
            this.lblResolutionTitle = new System.Windows.Forms.Label();

            // Creates the label used to display the estimated response time.
            this.lblResolutionEstimate = new System.Windows.Forms.Label();

            // Creates the label used to display an engagement message to the user.
            this.lblEngagementMsg = new System.Windows.Forms.Label();

            // Creates the button used to submit the issue report.
            this.btnSubmit = new System.Windows.Forms.Button();

            // Creates the button used to clear the information entered by the user.
            this.btnClear = new System.Windows.Forms.Button();

            // Creates the button used to return to the Main Menu.
            this.btnBack = new System.Windows.Forms.Button();

            // Creates the file selection dialog used when attaching a file.
            this.ofdAttachment = new System.Windows.Forms.OpenFileDialog();

            // Suspends the layout of the form while its controls are configured.
            this.SuspendLayout();


            // 
            // lblTitle
            // 

            // Allows the title label to automatically resize according to its text.
            this.lblTitle.AutoSize = true;

            // Sets the title font to bold with a larger size for visibility.
            this.lblTitle.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                14F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the title on the form.
            this.lblTitle.Location = new System.Drawing.Point(25, 20);

            // Assigns a unique name to the title label.
            this.lblTitle.Name = "lblTitle";

            // Defines the size of the title label.
            this.lblTitle.Size = new System.Drawing.Size(201, 29);

            // Sets the tab order position of the title label.
            this.lblTitle.TabIndex = 0;

            // Sets the text displayed at the top of the form.
            this.lblTitle.Text = "Report an Issue";


            // 
            // lblLocation
            // 

            // Allows the location label to automatically resize.
            this.lblLocation.AutoSize = true;

            // Sets the location label to bold to clearly identify the input field.
            this.lblLocation.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the location label.
            this.lblLocation.Location = new System.Drawing.Point(25, 68);

            // Assigns a unique name to the location label.
            this.lblLocation.Name = "lblLocation";

            // Defines the size of the location label.
            this.lblLocation.Size = new System.Drawing.Size(78, 18);

            // Sets the tab order position.
            this.lblLocation.TabIndex = 1;

            // Sets the label text.
            this.lblLocation.Text = "Location:";


            // 
            // txtLocation
            // 

            // Sets the font used for the location input field.
            this.txtLocation.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9.5F);

            // Sets the position of the location text box.
            this.txtLocation.Location = new System.Drawing.Point(140, 65);

            // Assigns a unique name to the text box.
            this.txtLocation.Name = "txtLocation";

            // Defines the width and height of the location text box.
            this.txtLocation.Size = new System.Drawing.Size(430, 25);

            // Sets the tab order position of the location input field.
            this.txtLocation.TabIndex = 2;


            // 
            // lblCategory
            // 

            // Allows the category label to automatically resize.
            this.lblCategory.AutoSize = true;

            // Sets the category label to bold.
            this.lblCategory.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the category label.
            this.lblCategory.Location = new System.Drawing.Point(25, 112);

            // Assigns a unique name to the category label.
            this.lblCategory.Name = "lblCategory";

            // Defines the size of the category label.
            this.lblCategory.Size = new System.Drawing.Size(81, 18);

            // Sets the tab order position.
            this.lblCategory.TabIndex = 3;

            // Sets the label text.
            this.lblCategory.Text = "Category:";


            // 
            // cmbCategory
            // 

            /**
             * Configures the category ComboBox so that users can only
             * select one of the predefined municipal service categories.
             * This prevents users from entering invalid or unexpected
             * category values.
             */
            this.cmbCategory.DropDownStyle =
                System.Windows.Forms.ComboBoxStyle.DropDownList;

            // Sets the font used by the category ComboBox.
            this.cmbCategory.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9.5F);

            // Enables formatting of the items displayed in the ComboBox.
            this.cmbCategory.FormattingEnabled = true;

            // Sets the position of the category ComboBox.
            this.cmbCategory.Location = new System.Drawing.Point(140, 108);

            // Assigns a unique name to the ComboBox.
            this.cmbCategory.Name = "cmbCategory";

            // Defines the size of the category ComboBox.
            this.cmbCategory.Size = new System.Drawing.Size(430, 28);

            // Sets the tab order position.
            this.cmbCategory.TabIndex = 4;

            /**
             * Connects the SelectedIndexChanged event to the corresponding
             * event handler. This allows the application to update the
             * estimated response time whenever the user selects a category.
             */
            this.cmbCategory.SelectedIndexChanged +=
                new System.EventHandler(this.cmbCategory_SelectedIndexChanged);


            // 
            // lblDescription
            // 

            // Allows the description label to automatically resize.
            this.lblDescription.AutoSize = true;

            // Sets the description label to bold.
            this.lblDescription.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the description label.
            this.lblDescription.Location = new System.Drawing.Point(25, 155);

            // Assigns a unique name to the label.
            this.lblDescription.Name = "lblDescription";

            // Defines the size of the description label.
            this.lblDescription.Size = new System.Drawing.Size(99, 18);

            // Sets the tab order position.
            this.lblDescription.TabIndex = 5;

            // Sets the label text.
            this.lblDescription.Text = "Description:";


            // 
            // rtbDescription
            // 

            // Sets the font used for the description input.
            this.rtbDescription.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9.5F);

            // Sets the position of the description box.
            this.rtbDescription.Location = new System.Drawing.Point(140, 152);

            // Assigns a unique name to the RichTextBox.
            this.rtbDescription.Name = "rtbDescription";

            // Defines the width and height of the description box.
            this.rtbDescription.Size = new System.Drawing.Size(430, 110);

            // Sets the tab order position.
            this.rtbDescription.TabIndex = 6;

            // Sets the initial description text to empty.
            this.rtbDescription.Text = "";


            // 
            // lblAttachment
            // 

            // Allows the attachment label to automatically resize.
            this.lblAttachment.AutoSize = true;

            // Sets the attachment label to bold.
            this.lblAttachment.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the attachment label.
            this.lblAttachment.Location = new System.Drawing.Point(25, 280);

            // Assigns a unique name to the label.
            this.lblAttachment.Name = "lblAttachment";

            // Defines the size of the attachment label.
            this.lblAttachment.Size = new System.Drawing.Size(97, 18);

            // Sets the tab order position.
            this.lblAttachment.TabIndex = 7;

            // Sets the label text.
            this.lblAttachment.Text = "Attachment:";


            // 
            // btnAttachFile
            // 

            // Sets the font used by the Attach File button.
            this.btnAttachFile.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F);

            // Sets the position of the Attach File button.
            this.btnAttachFile.Location = new System.Drawing.Point(140, 274);

            // Assigns a unique name to the button.
            this.btnAttachFile.Name = "btnAttachFile";

            // Defines the size of the button.
            this.btnAttachFile.Size = new System.Drawing.Size(100, 30);

            // Sets the tab order position.
            this.btnAttachFile.TabIndex = 8;

            // Sets the text displayed on the button.
            this.btnAttachFile.Text = "Attach File...";

            // Allows the button to use the default Windows visual style.
            this.btnAttachFile.UseVisualStyleBackColor = true;

            /**
             * Connects the button's Click event to the file attachment
             * event handler. When clicked, the user is presented with
             * a file selection dialog.
             */
            this.btnAttachFile.Click +=
                new System.EventHandler(this.btnAttachFile_Click);


            // 
            // lblAttachmentName
            // 

            // Allows the attachment filename label to automatically resize.
            this.lblAttachmentName.AutoSize = true;

            // Sets the font used for the attachment filename.
            this.lblAttachmentName.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F);

            // Sets the position of the attachment filename label.
            this.lblAttachmentName.Location = new System.Drawing.Point(250, 280);

            // Assigns a unique name to the label.
            this.lblAttachmentName.Name = "lblAttachmentName";

            // Defines the size of the label.
            this.lblAttachmentName.Size = new System.Drawing.Size(115, 18);

            // Sets the tab order position.
            this.lblAttachmentName.TabIndex = 9;

            // Displays the default message when no file is attached.
            this.lblAttachmentName.Text = "No file attached.";


            // 
            // btnRemoveAttachment
            // 

            // Sets the font used by the Remove button.
            this.btnRemoveAttachment.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F);

            // Sets the position of the Remove button.
            this.btnRemoveAttachment.Location = new System.Drawing.Point(490, 274);

            // Assigns a unique name to the button.
            this.btnRemoveAttachment.Name = "btnRemoveAttachment";

            // Defines the size of the button.
            this.btnRemoveAttachment.Size = new System.Drawing.Size(80, 30);

            // Sets the tab order position.
            this.btnRemoveAttachment.TabIndex = 10;

            // Sets the button text.
            this.btnRemoveAttachment.Text = "Remove";

            // Allows the button to use the default Windows visual style.
            this.btnRemoveAttachment.UseVisualStyleBackColor = true;

            // Hides the button until a file has been attached.
            this.btnRemoveAttachment.Visible = false;

            // Connects the button to the attachment removal event handler.
            this.btnRemoveAttachment.Click +=
                new System.EventHandler(this.btnRemoveAttachment_Click);


            // 
            // lblResolutionTitle
            // 

            // Allows the resolution title label to automatically resize.
            this.lblResolutionTitle.AutoSize = true;

            // Sets the label to bold so the response time information is clear.
            this.lblResolutionTitle.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the response time label.
            this.lblResolutionTitle.Location = new System.Drawing.Point(25, 325);

            // Assigns a unique name to the label.
            this.lblResolutionTitle.Name = "lblResolutionTitle";

            // Defines the size of the label.
            this.lblResolutionTitle.Size = new System.Drawing.Size(161, 18);

            // Sets the tab order position.
            this.lblResolutionTitle.TabIndex = 11;

            // Sets the label text.
            this.lblResolutionTitle.Text = "Est. Response Time:";


            // 
            // lblResolutionEstimate
            // 

            // Allows the response time label to automatically resize.
            this.lblResolutionEstimate.AutoSize = true;

            // Sets the response time text to bold for visibility.
            this.lblResolutionEstimate.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F,
                System.Drawing.FontStyle.Bold);

            // Sets the text colour used to highlight the response estimate.
            this.lblResolutionEstimate.ForeColor =
                System.Drawing.Color.DarkBlue;

            // Sets the position of the response estimate.
            this.lblResolutionEstimate.Location = new System.Drawing.Point(200, 325);

            // Assigns a unique name to the label.
            this.lblResolutionEstimate.Name = "lblResolutionEstimate";

            // Defines the size of the label.
            this.lblResolutionEstimate.Size = new System.Drawing.Size(184, 18);

            // Sets the tab order position.
            this.lblResolutionEstimate.TabIndex = 12;

            // Displays the default message before a category is selected.
            this.lblResolutionEstimate.Text = "Select a category above";


            // 
            // lblEngagementMsg
            // 

            // Allows the engagement message to automatically resize.
            this.lblEngagementMsg.AutoSize = true;

            // Uses an italic font to distinguish the supporting message.
            this.lblEngagementMsg.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                8.5F,
                System.Drawing.FontStyle.Italic);

            // Sets the message colour to a subtle grey.
            this.lblEngagementMsg.ForeColor =
                System.Drawing.Color.DimGray;

            // Sets the position of the engagement message.
            this.lblEngagementMsg.Location = new System.Drawing.Point(25, 355);

            // Assigns a unique name to the label.
            this.lblEngagementMsg.Name = "lblEngagementMsg";

            // Defines the size of the message label.
            this.lblEngagementMsg.Size = new System.Drawing.Size(430, 18);

            // Sets the tab order position.
            this.lblEngagementMsg.TabIndex = 13;

            // Displays the initial user engagement message.
            this.lblEngagementMsg.Text =
                "Reporting helps municipal response teams prioritize repair dispatches.";


            // 
            // btnSubmit
            // 

            // Sets the Submit button font to bold.
            this.btnSubmit.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9.5F,
                System.Drawing.FontStyle.Bold);

            // Sets the position of the Submit button.
            this.btnSubmit.Location = new System.Drawing.Point(460, 395);

            // Assigns a unique name to the button.
            this.btnSubmit.Name = "btnSubmit";

            // Defines the size of the Submit button.
            this.btnSubmit.Size = new System.Drawing.Size(110, 38);

            // Sets the tab order position.
            this.btnSubmit.TabIndex = 14;

            // Sets the button text.
            this.btnSubmit.Text = "Submit";

            // Allows the button to use the default Windows visual style.
            this.btnSubmit.UseVisualStyleBackColor = true;

            /**
             * Connects the Submit button to the submission event handler.
             * When clicked, the application validates the user's information
             * and creates a new municipal issue report.
             */
            this.btnSubmit.Click +=
                new System.EventHandler(this.btnSubmit_Click);


            // 
            // btnClear
            // 

            // Sets the font used by the Clear button.
            this.btnClear.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F);

            // Sets the position of the Clear button.
            this.btnClear.Location = new System.Drawing.Point(340, 395);

            // Assigns a unique name to the button.
            this.btnClear.Name = "btnClear";

            // Defines the size of the Clear button.
            this.btnClear.Size = new System.Drawing.Size(100, 38);

            // Sets the tab order position.
            this.btnClear.TabIndex = 15;

            // Sets the button text.
            this.btnClear.Text = "Clear";

            // Allows the button to use the default Windows visual style.
            this.btnClear.UseVisualStyleBackColor = true;

            // Connects the Clear button to the form reset event handler.
            this.btnClear.Click +=
                new System.EventHandler(this.btnClear_Click);


            // 
            // btnBack
            // 

            // Sets the font used by the Back button.
            this.btnBack.Font = new System.Drawing.Font(
                "Microsoft Sans Serif",
                9F);

            // Sets the position of the Back button.
            this.btnBack.Location = new System.Drawing.Point(25, 395);

            // Assigns a unique name to the button.
            this.btnBack.Name = "btnBack";

            // Defines the size of the Back button.
            this.btnBack.Size = new System.Drawing.Size(100, 38);

            // Sets the tab order position.
            this.btnBack.TabIndex = 16;

            // Sets the button text.
            this.btnBack.Text = "Back";

            // Allows the button to use the default Windows visual style.
            this.btnBack.UseVisualStyleBackColor = true;

            // Connects the Back button to the navigation event handler.
            this.btnBack.Click +=
                new System.EventHandler(this.btnBack_Click);


            // 
            // ofdAttachment
            // 

            /**
             * Defines the file types that users can select when attaching
             * supporting evidence to a municipal issue report.
             *
             * The application accepts common image and document formats,
             * including JPG, PNG, PDF, DOCX and TXT files.
             */
            this.ofdAttachment.Filter =
                "Files (*.jpg;*.png;*.pdf;*.docx;*.txt)|*.jpg;*.png;*.pdf;*.docx;*.txt|All Files (*.*)|*.*";

            // Sets the title displayed at the top of the file selection dialog.
            this.ofdAttachment.Title = "Select File";


            // 
            // ReportIssuesForm
            // 

            // Defines the scaling dimensions used by the form.
            this.AutoScaleDimensions =
                new System.Drawing.SizeF(8F, 16F);

            // Sets the automatic scaling mode based on the form's font.
            this.AutoScaleMode =
                System.Windows.Forms.AutoScaleMode.Font;

            // Defines the width and height of the Report Issues window.
            this.ClientSize =
                new System.Drawing.Size(600, 455);

            // Adds the Back button to the form.
            this.Controls.Add(this.btnBack);

            // Adds the Clear button to the form.
            this.Controls.Add(this.btnClear);

            // Adds the Submit button to the form.
            this.Controls.Add(this.btnSubmit);

            // Adds the engagement message to the form.
            this.Controls.Add(this.lblEngagementMsg);

            // Adds the response time estimate to the form.
            this.Controls.Add(this.lblResolutionEstimate);

            // Adds the response time title to the form.
            this.Controls.Add(this.lblResolutionTitle);

            // Adds the Remove Attachment button to the form.
            this.Controls.Add(this.btnRemoveAttachment);

            // Adds the attachment filename label to the form.
            this.Controls.Add(this.lblAttachmentName);

            // Adds the Attach File button to the form.
            this.Controls.Add(this.btnAttachFile);

            // Adds the Attachment label to the form.
            this.Controls.Add(this.lblAttachment);

            // Adds the description input area to the form.
            this.Controls.Add(this.rtbDescription);

            // Adds the Description label to the form.
            this.Controls.Add(this.lblDescription);

            // Adds the category selection box to the form.
            this.Controls.Add(this.cmbCategory);

            // Adds the Category label to the form.
            this.Controls.Add(this.lblCategory);

            // Adds the location input field to the form.
            this.Controls.Add(this.txtLocation);

            // Adds the Location label to the form.
            this.Controls.Add(this.lblLocation);

            // Adds the title label to the form.
            this.Controls.Add(this.lblTitle);

            // Prevents the user from resizing the window.
            this.FormBorderStyle =
                System.Windows.Forms.FormBorderStyle.FixedSingle;

            // Disables the maximise button.
            this.MaximizeBox = false;

            // Assigns the internal name of the form.
            this.Name = "ReportIssuesForm";

            // Positions the form in the centre of the user's screen.
            this.StartPosition =
                System.Windows.Forms.FormStartPosition.CenterScreen;

            // Sets the text displayed in the application window title bar.
            this.Text = "Report Issues";

            /**
             * Connects the form's Load event to the ReportIssuesForm_Load
             * event handler. This allows the categories to be populated
             * and the form to be reset when it is opened.
             */
            this.Load +=
                new System.EventHandler(this.ReportIssuesForm_Load);

            // Resumes the layout of the form after all controls are configured.
            this.ResumeLayout(false);

            // Applies the final layout settings to the controls.
            this.PerformLayout();

        }

        #endregion


        // Label displaying the title of the Report Issues form.
        private System.Windows.Forms.Label lblTitle;

        // Label identifying the location input field.
        private System.Windows.Forms.Label lblLocation;

        // Text box used to enter the location of the municipal issue.
        private System.Windows.Forms.TextBox txtLocation;

        // Label identifying the issue category selection.
        private System.Windows.Forms.Label lblCategory;

        // ComboBox used to select the type of municipal issue.
        private System.Windows.Forms.ComboBox cmbCategory;

        // Label identifying the issue description field.
        private System.Windows.Forms.Label lblDescription;

        // RichTextBox used to enter a detailed description of the issue.
        private System.Windows.Forms.RichTextBox rtbDescription;

        // Label identifying the attachment section.
        private System.Windows.Forms.Label lblAttachment;

        // Button used to select and attach a supporting file.
        private System.Windows.Forms.Button btnAttachFile;

        // Label displaying the name of the selected attachment.
        private System.Windows.Forms.Label lblAttachmentName;

        // Button used to remove the selected attachment.
        private System.Windows.Forms.Button btnRemoveAttachment;

        // Label identifying the estimated response time.
        private System.Windows.Forms.Label lblResolutionTitle;

        // Label displaying the estimated response time for the selected category.
        private System.Windows.Forms.Label lblResolutionEstimate;

        // Label displaying an engagement message to encourage detailed reporting.
        private System.Windows.Forms.Label lblEngagementMsg;

        // Button used to submit the completed issue report.
        private System.Windows.Forms.Button btnSubmit;

        // Button used to clear all information entered into the form.
        private System.Windows.Forms.Button btnClear;

        // Button used to return to the Main Menu.
        private System.Windows.Forms.Button btnBack;

        // Provides the file selection dialog for attaching supporting evidence.
        private System.Windows.Forms.OpenFileDialog ofdAttachment;
    }
}